import { ThemeContextProvider } from "@/components/store/ThemeContext";
import "./globals.css";

export const metadata = {
  title: "Nelson Carv Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeContextProvider>{children}</ThemeContextProvider>
      </body>
    </html>
  );
}
